import { Montserrat } from "next/font/google";
import "./globals.css";
import LayoutWrapper from "@/components/layout-wrapper";
import Providers from "@/components/providers";

const spotifyFont = Montserrat({
  subsets: ["latin"],
  weight: ["400", "700", "900"],
});

export const metadata = {
  title: "Spotify",
  description: "Generated by create next app",
  metadataBase: new URL(process.env.NEXT_PUBLIC_SITE_URL || "http://localhost:3000"),
  keywords: ["music", "spotify", "streaming", "songs", "playlists", "artists", "albums"],
  authors: [{ name: "Spotify" }],
  creator: "Spotify",
  publisher: "Spotify",
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  openGraph: {
    type: "website",
    locale: "en_US",
    url: process.env.NEXT_PUBLIC_SITE_URL || "http://localhost:3000",
    siteName: "Spotify",
    title: "Spotify - Music Streaming",
    description: "Listen to millions of songs, artists, and albums. Create playlists and discover new music.",
    images: [
      {
        url: "/logo/spotify.png",
        width: 1200,
        height: 630,
        alt: "Spotify",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "Spotify - Music Streaming",
    description: "Listen to millions of songs, artists, and albums. Create playlists and discover new music.",
    images: ["/logo/spotify.png"],
    creator: "@spotify",
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  verification: {
    google: process.env.GOOGLE_VERIFICATION,
    yandex: process.env.YANDEX_VERIFICATION,
    yahoo: process.env.YAHOO_VERIFICATION,
  },
  alternates: {
    canonical: process.env.NEXT_PUBLIC_SITE_URL || "http://localhost:3000",
  },
};

export default function RootLayout({ children }) {
  const baseUrl = process.env.NEXT_PUBLIC_SITE_URL || "http://localhost:3000";

  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/logo/spotify.png" />
        <link rel="apple-touch-icon" href="/logo/spotify.png" />
        <meta name="theme-color" content="#1DB954" />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "WebSite",
              name: "Spotify",
              url: baseUrl,
              description: "Music streaming platform",
              potentialAction: {
                "@type": "SearchAction",
                target: {
                  "@type": "EntryPoint",
                  urlTemplate: `${baseUrl}/search?q={search_term_string}`,
                },
                "query-input": "required name=search_term_string",
              },
            }),
          }}
        />
      </head>
      <body className={spotifyFont.className} suppressHydrationWarning>
        <Providers>
          <LayoutWrapper>{children}</LayoutWrapper>
        </Providers>
      </body>
    </html>
  );
}
